- platform: template
  sensors:
    kaffekoker:
      friendly_name: "Kaffekoker"
      device_class: power
      icon_template: mdi:coffee-maker
      value_template: "{{ states('sensor.kaffekoker_power') | float(0) > 10.0 }}"
    avfukter:
      friendly_name: "Avfukter"
      device_class: power
      icon_template: mdi:air-humidifier
      value_template: "{{ states('sensor.vaskerom_avfukter_power') | float(0) > 10.0 }}"
    oppvaskmaskin:
      friendly_name: "Oppvaskmaskin"
      delay_off: "00:05:00"
      device_class: power
      icon_template: mdi:dishwasher
      value_template: "{{ states('sensor.kjokken_oppvaskmaskin_power') | float(0) > 1.0 }}"
    vaskemaskin:
      friendly_name: "Vaskemaskin"
      delay_off: "00:12:00"
      device_class: power
      icon_template: mdi:washing-machine
      value_template: "{{ states('sensor.vaskerom_vaskemaskin_power') | float(0) > 10.0 }}"
    torketrommel:
      friendly_name: "Tørketrommel"
      delay_off: "00:22:00"
      device_class: power
      icon_template: mdi:tumble-dryer
      value_template: "{{ states('sensor.vaskerom_torketrommel_power') | float(0) > 10.0 }}"
    platetopp:
      friendly_name: "Platetopp"
      delay_off: "00:05:00"
      device_class: power
      icon_template: mdi:heat-wave
      value_template: "{{ states('sensor.kjokken_platetopp_sensor_power') | float(0) > 15.0 }}"
    stekeovn:
      friendly_name: "Stekeovn"
      delay_off: "00:05:00"
      device_class: power
      icon_template: mdi:toaster-oven
      value_template: "{{ states('sensor.kjokken_stekeovn_power') | float(0) > 15.0 }}"

    priceanalyzer_is_five_cheapest:
      friendly_name: "Price Analyzer - Laveste 5h strømpris"
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim_2', 'current_hour').is_five_cheapest }}"
    priceanalyzer_is_ten_cheapest:
      friendly_name: "Price Analyzer - Laveste 10h strømpris"
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim_2', 'current_hour').is_ten_cheapest }}"
