- platform: template
  sensors:
    kaffekoker:
      friendly_name: "Kaffekoker"
      device_class: power
      icon_template: mdi:coffee-maker
      value_template: "{{ states('sensor.kaffekoker_power') | float(0) > 10.0 }}"
    avfukter:
      friendly_name: "Avfukter"
      device_class: power
      icon_template: mdi:air-humidifier
      value_template: "{{ states('sensor.vaskerom_avfukter_power') | float(0) > 10.0 }}"
    oppvaskmaskin:
      friendly_name: "Oppvaskmaskin"
      delay_off: "00:10:00"
      device_class: power
      icon_template: mdi:dishwasher
      value_template: "{{ states('sensor.kjokken_oppvaskmaskin_power') | float(0) > 10.0 }}"
    vaskemaskin:
      friendly_name: "Vaskemaskin"
      delay_off: "00:12:00"
      device_class: power
      icon_template: mdi:washing-machine
      value_template: "{{ states('sensor.vaskerom_vaskemaskin_power') | float(0) > 10.0 }}"
    torketrommel:
      friendly_name: "Tørketrommel"
      delay_off: "00:22:00"
      device_class: power
      icon_template: mdi:tumble-dryer
      value_template: "{{ states('sensor.vaskerom_torketrommel_power') | float(0) > 10.0 }}"
    platetopp:
      friendly_name: "Platetopp"
      delay_off: "00:05:00"
      device_class: power
      icon_template: mdi:heat-wave
      value_template: "{{ states('sensor.kjokken_platetopp_sensor_power') | float(0) > 15.0 }}"
    stekeovn:
      friendly_name: "Stekeovn"
      delay_off: "00:05:00"
      device_class: power
      icon_template: mdi:toaster-oven
      value_template: "{{ states('sensor.kjokken_stekeovn_power') | float(0) > 15.0 }}"
    jonas_klokke:
      friendly_name: "Jonas klokke"
      device_class: battery
      icon_template: mdi:watch
      value_template: "{{ states('sensor.jonas_langen_kaberg_watch_battery') | float(0) < 35.0 }}"
    dark_outside:
      friendly_name: "Mørkt ute"
      icon_template: mdi:wb_twighlight
      value_template: "{{ states('sensor.st_00117532_belysningsstyrke') | float(0) < 350.0 }}"