- platform: template
  covers:
    garage_port:
      device_class: garage
      friendly_name: "Garage Port"
      value_template: "{{ states('pyscript.GARAGE_DIRECTION') }}"
      position_template: "{{ states('sensor.ble_opening_percentage_ble_garage_port') | float(0) }}"
      open_cover:
        service: switch.turn_on
        entity_id: switch.garasje_port_5
      close_cover:
        service: switch.turn_on
        entity_id: switch.garasje_port_5
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garasje_port_5
