- platform: rflink
  automatic_add: false

- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port

- platform: time_date
  display_options:
    - 'time'


# https://www.tensio.no/no/kunde/nettleie/nettleiepriser-for-privat
- platform: energytariff
  entity_id: "sensor.strommaler_power"
  levels:
  - name: "Trinn 1: 0-2 kWh"
    threshold: 2
    price: 137
  - name: "Trinn 2: 2-5 kWh"
    threshold: 5
    price: 244
  - name: "Trinn 3: 5-10 kWh"
    threshold: 10
    price: 416
  - name: "Trinn 4: 10-15 kWh"
    threshold: 15
    price: 613
