- platform: rflink
  automatic_add: false

- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port

- platform: time_date
  display_options:
    - 'time'

- platform: energytariff
  entity_id: "sensor.strommaler_power"
  levels:
  - name: "Trinn 1: 0-2 kWh"
    threshold: 2
    price: 134
  - name: "Trinn 2: 2-5 kWh"
    threshold: 5
    price: 239
  - name: "Trinn 3: 5-10 kWh"
    threshold: 10
    price: 408
  - name: "Trinn 4: 10-15 kWh"
    threshold: 15
    price: 601
  - name: "Trinn 5: 15-20 kWh"
    threshold: 20
    price: 794

# Brukes med ENTSO-E integrasjonen ift konvertering av EUR til NOK
# for beregning av strømrpis
- platform: rest
  resource: https://data.norges-bank.no/api/data/EXR/B.EUR.NOK.SP?lastNObservations=1&format=sdmx-json
  name: kurs_eur
  scan_interval: 43200
  unit_of_measurement: NOK
  value_template: "{{ value_json['data']['dataSets'][0]['series']['0:0:0:0']['observations']['0'][0] }}"