- platform: time_date
  display_options:
    - 'time'

- platform: nordpool
  VAT: True
  currency: "NOK"
  region: "Tr.heim"
  precision: 2 

- platform: priceanalyzer
  VAT: True
  currency: "NOK"
  region: "Tr.heim"
  price_type: kWh
  additional_costs: >-
    {% set s = {
        "day": 0.3626,
        "night": 0.2839
    }
    %}
    {% if now().weekday() in [5, 6] %} # saturday and sunday
        {{ s.night | float }}
    {% elif now().hour >= 6 and now().hour < 23 %}
        {{ s.day | float }}
    {% else %}
        {{ s.night | float }}
    {% endif %}

- platform: integration
  name: energy_per_hour2
  unique_id: energy_per_hour2
  source: sensor.strommaler_power
  unit_prefix: k
  method: left

- platform: template
  sensors:
    azimuth:
      friendly_name: "Sun Azimuth"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
    panasonic_ac_inside_temperature:
      friendly_name: "Inside temperature"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.panasonic_ac', 'current_temperature') }}"
    vaskerom_vvb_temperatur:
      friendly_name: "VVB temperatur justert"
      icon_template: mdi:coolant-temperature
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.vaskerom_vvb_air_temperature_2') | float(0) + 19.0 | float(0))  | round(1) }}"
    vaskerom_vvb_watt_corrected:
      unit_of_measurement: 'W'
      friendly_name: 'VVB effekt justert'  
      icon_template: mdi:sine-wave  
      value_template: >-
        {% if is_state('switch.vaskerom_vvb', 'on') %}
          {% set corrected_watt = states('sensor.vaskerom_vvb_electric_consumption_w') | float(0) - 354.0 %} # adjust for bad measurement
          {% if corrected_watt > 25.0 %} # mitigate negative vakues and "false positives"
            {{ corrected_watt }}
          {% else %}
            0.0
          {% endif %}
        {% else %}
          0.0
        {% endif %}

    priceanalyzer_current_price:
      friendly_name: "Nåværende strømpris"
      unit_of_measurement: 'NOK/kWh'
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim', 'value') }}"
    priceanalyzer_is_ten_cheapest:
      friendly_name: "Laveste 10h strømpris"
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim', 'is_ten_cheapest') }}"
    priceanalyzer_is_five_cheapest:
      friendly_name: "Laveste 5h strømpris"
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim', 'is_five_cheapest') }}"

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_15m
    - type: load_5m
    - type: load_1m