- platform: time_date
  display_options:
    - 'time'

- platform: integration
  name: energy_per_hour2
  unique_id: energy_per_hour2
  source: sensor.strommaler_power
  unit_prefix: k
- platform: integration
  name: panasonic_ac_2_consumption_kwh
  unique_id: panasonic_ac_2_consumption_kwh
  source: sensor.panasonic_ac_power_consumption
  unit_prefix: k
  method: left

- platform: derivative
  source: sensor.energy_per_hour2
  name: Derivert effekt
  round: 1
  unit_time: "h"
  time_window: "00:05:00"

- platform: energytariff
  entity_id: "sensor.strommaler_power"
  levels:
  - name: "Trinn 1: 0-2 kWh"
    threshold: 2
    price: 83
  - name: "Trinn 2: 2-5 kWh"
    threshold: 5
    price: 147
  - name: "Trinn 3: 5-10 kWh"
    threshold: 10
    price: 252
  - name: "Trinn 4: 10-15 kWh"
    threshold: 15
    price: 371
  - name: "Trinn 5: 15-20 kWh"
    threshold: 20
    price: 490

- platform: template
  sensors:
    azimuth:
      friendly_name: "Sun Azimuth"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
    vaskerom_vvb_temp_corrected:
      friendly_name: "VVB temperatur justert"
      icon_template: mdi:coolant-temperature
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.vaskerom_vvb_air_temperature_2') | float(0) + 24.5) }}"
    vaskerom_vvb_watt_corrected:
      unit_of_measurement: 'W'
      friendly_name: 'VVB effekt justert'  
      icon_template: mdi:sine-wave  
      value_template: >-
        {% if is_state('switch.vaskerom_vvb', 'on') %}
          {% set corrected_watt = states('sensor.vaskerom_vvb_electric_consumption_w') | float(0) - 354.0 %}
          {% if corrected_watt > 25.0 %}
            {{ corrected_watt }}
          {% else %}
            0.0
          {% endif %}
        {% else %}
          0.0
        {% endif %}
    current_energy_consumption_kwh:
      friendly_name: "Nygårdsvegen 6 nåværende forbruk kWh"
      unique_id: sensor.current_energy_consumption_kwh
      unit_of_measurement: 'kW'
      device_class: 'power'
      value_template: "{{ (states('sensor.strommaler_power') | float(0) / 1000) }}"
    current_energy_cost_kwh:
      friendly_name: "Nygårdsvegen 6 nåværende forbruk kostnad"
      unique_id: sensor.current_energy_cost_kwh
      unit_of_measurement: 'NOK'
      device_class: 'monetary'
      value_template: "{{ (states('sensor.current_energy_consumption_kwh') | float(0)) * (states('sensor.energy_price_with_tarif') | float(0)) }}"

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_15m
    - type: load_5m
    - type: load_1m


- platform: filter
  name: "Elbillader filtered"
  unique_id: sensor.garasje_lifetime_energy
  entity_id: sensor.garasje_lifetime_energy
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme inngang filtered"
  unique_id: sensor.gulvvarme_inngang_value_electric_consumed_4
  entity_id: sensor.gulvvarme_inngang_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Varmtvannsbereder filtered"
  unique_id: sensor.vaskerom_vvb_consumption_kwh_corrected
  entity_id: sensor.vaskerom_vvb_consumption_kwh_corrected
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Panelovn Jonas rom filtered"
  unique_id: sensor.panelovn_stort_soverom_electric_production_kwh
  entity_id: sensor.panelovn_stort_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Panelovn hovedsoverom filtered"
  unique_id: sensor.panelovn_hovedsoverom_electric_production_kwh
  entity_id: sensor.panelovn_hovedsoverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Panelovn Sofies rom filtered"
  unique_id: sensor.panelovn_mellom_soverom_electric_production_kwh
  entity_id: sensor.panelovn_mellom_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Panelovn Markus rom filtered"
  unique_id: sensor.panelovn_litet_soverom_electric_production_kwh
  entity_id: sensor.panelovn_litet_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme bad 1 etg filtered"
  unique_id: sensor.gulvvarme_bad_1_etg_value_electric_consumed_4
  entity_id: sensor.gulvvarme_bad_1_etg_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme tv stua filtered"
  unique_id: sensor.gulvvarme_tv_stue_value_electric_consumed_4
  entity_id: sensor.gulvvarme_tv_stue_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Utelys sør filtered"
  unique_id: sensor.utelys_sor_electric_consumption_kwh
  entity_id: sensor.utelys_sor_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme stua filtered"
  unique_id: sensor.gulvvarme_stue_electric_consumed_kwh_4
  entity_id: sensor.gulvvarme_stue_electric_consumed_kwh_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme kjøkken filtered"
  unique_id: sensor.gulvvarme_kjokken_value_electric_consumed_4
  entity_id: sensor.gulvvarme_kjokken_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Utelys nord filtered"
  unique_id: sensor.utelys_nord_electric_consumption_kwh
  entity_id: sensor.utelys_nord_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Vaskemaskin filtered"
  unique_id: sensor.vaskerom_vaskemaskin_energy
  entity_id: sensor.vaskerom_vaskemaskin_energy
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Gulvvarme bad 2 etg filtered"
  unique_id: sensor.gulvvarme_bad_2_etg_value_electric_consumed_4
  entity_id: sensor.gulvvarme_bad_2_etg_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Tørketrommel filtered"
  unique_id: sensor.vaskerom_torketrommel_energy
  entity_id: sensor.vaskerom_torketrommel_energy
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Avfukter vaskerom filtered"
  unique_id: sensor.vaskerom_avfukter_energy
  entity_id: sensor.vaskerom_avfukter_energy
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Panelovn kontor filtered"
  unique_id: sensor.panelovn_kontor_electric_production_kwh
  entity_id: sensor.panelovn_kontor_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Kaffekoker filtered"
  unique_id: sensor.kaffekoker_energy
  entity_id: sensor.kaffekoker_energy
  filters:
    - filter: outlier
      window_size: 4
- platform: filter
  name: "Oppvaskmaskin filtered"
  unique_id: sensor.kjokken_oppvaskmaskin_energy
  entity_id: sensor.kjokken_oppvaskmaskin_energy
  filters:
    - filter: outlier
      window_size: 4