- platform: time_date
  display_options:
    - 'time'

- platform: integration
  name: energy_per_hour2
  unique_id: energy_per_hour2
  source: sensor.strommaler_power
  unit_prefix: k

- platform: derivative
  source: sensor.energy_per_hour2
  name: Derivert effekt
  round: 1
  unit_time: "h"
  time_window: "00:05:00"

- platform: template
  sensors:
    azimuth:
      friendly_name: "Sun Azimuth"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
    panasonic_ac_inside_temperature:
      friendly_name: "Inside temperature"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.panasonic_ac', 'current_temperature') }}"
    vaskerom_vvb_temp_corrected:
      friendly_name: "VVB temperatur justert"
      icon_template: mdi:coolant-temperature
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.vaskerom_vvb_air_temperature_2') | float(0) + 24.5) }}"
    vaskerom_vvb_watt_corrected:
      unit_of_measurement: 'W'
      friendly_name: 'VVB effekt justert'  
      icon_template: mdi:sine-wave  
      value_template: >-
        {% if is_state('switch.vaskerom_vvb', 'on') %}
          {% set corrected_watt = states('sensor.vaskerom_vvb_electric_consumption_w') | float(0) - 354.0 %}
          {% if corrected_watt > 25.0 %}
            {{ corrected_watt }}
          {% else %}
            0.0
          {% endif %}
        {% else %}
          0.0
        {% endif %}
    priceanalyzer_current_price:
      friendly_name: "Nåværende strømpris"
      device_class: monetary
      unit_of_measurement: NOK/kWh
      value_template: "{{ state_attr('sensor.priceanalyzer_tr_heim_2', 'current_hour').value }}"
    estimated_hourly_consumption:
      friendly_name: "Estimert Timeforbruk"
      unit_of_measurement: 'kWh'
      device_class: power
      value_template: "{{ (states('sensor.nygardsvegen_6_forbruk') | float(15) + states('sensor.derivert_effekt') | float(0) * (3600 - now().minute * 60 - now().second) / 3600) | round(3) }}"

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_15m
    - type: load_5m
    - type: load_1m

- platform: filter
  name: "Elbillader filtered"
  unique_id: sensor.garasje_lifetime_energy
  entity_id: sensor.garasje_lifetime_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn inngang filtered"
  unique_id: sensor.panelovn_inngang_electric_production_kwh
  entity_id: sensor.panelovn_inngang_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme inngang filtered"
  unique_id: sensor.gulvvarme_inngang_value_electric_consumed_4
  entity_id: sensor.gulvvarme_inngang_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Varmtvannsbereder filtered"
  unique_id: sensor.vaskerom_vvb_consumption_kwh_corrected
  entity_id: sensor.vaskerom_vvb_consumption_kwh_corrected
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn Jonas rom filtered"
  unique_id: sensor.panelovn_stort_soverom_electric_production_kwh
  entity_id: sensor.panelovn_stort_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn hovedsoverom filtered"
  unique_id: sensor.panelovn_hovedsoverom_electric_production_kwh
  entity_id: sensor.panelovn_hovedsoverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn Sofies rom filtered"
  unique_id: sensor.panelovn_mellom_soverom_electric_production_kwh
  entity_id: sensor.panelovn_mellom_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn Markus rom filtered"
  unique_id: sensor.panelovn_litet_soverom_electric_production_kwh
  entity_id: sensor.panelovn_litet_soverom_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme bad 1 etg filtered"
  unique_id: sensor.gulvvarme_bad_1_etg_value_electric_consumed_4
  entity_id: sensor.gulvvarme_bad_1_etg_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme tv stua filtered"
  unique_id: sensor.gulvvarme_tv_stue_value_electric_consumed_4
  entity_id: sensor.gulvvarme_tv_stue_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Utelys sør filtered"
  unique_id: sensor.utelys_sor_electric_consumption_kwh
  entity_id: sensor.utelys_sor_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme stua filtered"
  unique_id: sensor.gulvvarme_stue_electric_consumed_kwh_4
  entity_id: sensor.gulvvarme_stue_electric_consumed_kwh_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme kjøkken filtered"
  unique_id: sensor.gulvvarme_kjokken_value_electric_consumed_4
  entity_id: sensor.gulvvarme_kjokken_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Utelys nord filtered"
  unique_id: sensor.utelys_nord_electric_consumption_kwh
  entity_id: sensor.utelys_nord_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Vaskemaskin filtered"
  unique_id: sensor.vaskerom_vaskemaskin_energy
  entity_id: sensor.vaskerom_vaskemaskin_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Gulvvarme bad 2 etg filtered"
  unique_id: sensor.gulvvarme_bad_2_etg_value_electric_consumed_4
  entity_id: sensor.gulvvarme_bad_2_etg_value_electric_consumed_4
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Tørketrommel filtered"
  unique_id: sensor.vaskerom_torketrommel_energy
  entity_id: sensor.vaskerom_torketrommel_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Avfukter vaskerom filtered"
  unique_id: sensor.vaskerom_avfukter_energy
  entity_id: sensor.vaskerom_avfukter_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Panelovn kontor filtered"
  unique_id: sensor.panelovn_kontor_electric_production_kwh
  entity_id: sensor.panelovn_kontor_electric_production_kwh
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Kaffekoker filtered"
  unique_id: sensor.kaffekoker_energy
  entity_id: sensor.kaffekoker_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
- platform: filter
  name: "Oppvaskmaskin filtered"
  unique_id: sensor.kjokken_oppvaskmaskin_energy
  entity_id: sensor.kjokken_oppvaskmaskin_energy
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0